import type { Metadata } from 'next';
import { AlertTriangle } from 'lucide-react';
import { getCurrentOrg } from '@/lib/org';
import { createClient } from '@/lib/supabase/server';
import { getAvailableYears } from './actions';
import W2Generator from './_components/w2-generator';
import Form1099 from './_components/form-1099';
import TaxReport from './_components/tax-report';
import type { Employee } from '../payroll/actions';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = { title: 'Tax' };

export default async function TaxPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | undefined>>;
}) {
  const params = await searchParams;
  const tab = params.tab ?? 'w2';

  const { org } = await getCurrentOrg();
  const supabase = await createClient();

  const [{ data: employees }, availableYears] = await Promise.all([
    supabase
      .from('employees')
      .select('id, name, role, hourly_rate, tip_mode')
      .eq('organization_id', org.id)
      .order('name'),
    getAvailableYears(),
  ]);

  const empList = (employees ?? []) as Employee[];
  const TABS = [
    { key: 'w2',     label: 'W-2 Forms' },
    { key: '1099',   label: '1099-NEC' },
    { key: 'report', label: 'Tax Report' },
  ];

  return (
    <div className="p-6 space-y-6 max-w-6xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Tax</h1>
        <p className="text-muted-foreground">Generate W-2s, 1099s, and tax summaries from your payroll data</p>
      </div>

      {/* Disclaimer banner */}
      <div className="flex gap-3 rounded-xl border border-amber-500/30 bg-amber-500/8 px-5 py-4">
        <AlertTriangle className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="text-sm font-semibold text-amber-300">Legal Disclaimer — Read Before Use</p>
          <p className="text-xs text-amber-300/70 leading-relaxed">
            Documents generated by Rail are <strong>unofficial drafts for reference only</strong> and are NOT valid IRS tax forms.
            Do not file them with the IRS, employees, or any government agency without review by a licensed CPA or tax professional.
            Rail is not responsible or legally liable for errors, omissions, or any tax penalties arising from use of these outputs.
            All figures are based solely on data imported into Rail and may be incomplete.
            Tax law varies by state and locality — always consult a qualified professional before filing.
          </p>
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b">
        <div className="flex gap-8">
          {TABS.map(({ key, label }) => (
            <a
              key={key}
              href={`/app/tax?tab=${key}`}
              className={`px-1 pb-4 text-sm font-medium border-b-2 transition-colors ${
                tab === key
                  ? 'border-primary text-primary'
                  : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
            >
              {label}
            </a>
          ))}
        </div>
      </div>

      {/* Tab content */}
      {tab === 'w2' && (
        <W2Generator
          availableYears={availableYears}
          employees={empList}
          orgName={org.name}
        />
      )}
      {tab === '1099' && (
        <Form1099
          availableYears={availableYears}
          employees={empList}
          orgName={org.name}
        />
      )}
      {tab === 'report' && <TaxReport orgName={org.name} />}
    </div>
  );
}
