'use server';

import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import { createAdminClient } from '@/lib/supabase/admin';
import { getAuthUser, getCurrentOrg } from '@/lib/org';
import { canManagePayroll } from '@/lib/permissions';
import {
  PAYOUT_METHODS, remainingAdvanceCapacity, totalPaidTo,
  type Payout, type PayoutMethod,
} from '@/lib/payroll/payouts';
import { computePayroll } from './actions';

/**
 * Marking who has actually been paid for a period.
 *
 * Unpaid is the absence of a row, so there are only two writes: insert one, or
 * delete it. See the migration for why there is no status column.
 *
 * Both writes check the caller may manage payroll and that the employee belongs
 * to the caller's bar — `employee_id` arrives from the client, and without that
 * check a crafted id would attach a payout to another bar's staff.
 */

const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Expected YYYY-MM-DD');

/** Whole dollars and cents, for an error message a person has to act on. */
const money = (n: number) =>
  n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });

const markSchema = z.object({
  employeeId:  z.string().uuid(),
  periodStart: isoDate,
  periodEnd:   isoDate,
  method:      z.enum(PAYOUT_METHODS as unknown as [PayoutMethod, ...PayoutMethod[]]),
  // What the run said this person was owed at the moment of marking. Negative
  // is impossible; the ceiling is a typo guard, not a policy.
  amountPaid:  z.number().min(0).max(1_000_000),
  // The nights the amount was worked out from. Null for a whole-period payout,
  // which is what "Mark paid" still does.
  coversDays:  z.array(isoDate).nullable().optional(),
  // Generated by the client when the dialog opens, so the same tap twice
  // collides on the unique index instead of paying somebody a second time.
  idempotencyKey: z.string().uuid(),
});

const deleteSchema = z.object({ payoutId: z.string().uuid() });

export type PayoutResult = { ok: boolean; error?: string };

/** Every payout recorded for the period on screen, keyed by employee. */
export async function loadPayouts(
  periodStart: string,
  periodEnd: string,
): Promise<Payout[]> {
  const { org } = await getCurrentOrg();
  const supabase = createAdminClient();

  const { data } = await supabase
    .from('payroll_payouts')
    .select('id, employee_id, method, amount_paid, paid_at, covers_days')
    .eq('organization_id', org.id)
    .eq('period_start', periodStart)
    .eq('period_end', periodEnd)
    // Oldest first: the payments list reads as a history, and an advance
    // precedes the settlement it was taken against.
    .order('paid_at', { ascending: true });

  return (data ?? []).map((row) => ({
    id:         row.id as string,
    employeeId: row.employee_id as string,
    method:     row.method as PayoutMethod,
    // NUMERIC comes back as a string on some driver versions; the UI formats it.
    amountPaid: Number(row.amount_paid ?? 0),
    paidAt:     row.paid_at as string,
    coversDays: (row.covers_days as string[] | null) ?? null,
  }));
}

/** Confirms the employee is at the caller's bar before anything is written. */
async function assertEmployeeInOrg(
  supabase: ReturnType<typeof createAdminClient>,
  orgId: string,
  employeeId: string,
): Promise<boolean> {
  const { data } = await supabase
    .from('employees')
    .select('id')
    .eq('id', employeeId)
    .eq('organization_id', orgId)
    .maybeSingle();
  return Boolean(data);
}

export async function markPaid(input: {
  employeeId: string;
  periodStart: string;
  periodEnd: string;
  method: PayoutMethod;
  amountPaid: number;
  coversDays?: string[] | null;
  idempotencyKey: string;
}): Promise<PayoutResult> {
  const parsed = markSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'Invalid payout' };
  }

  const { org, role } = await getCurrentOrg();
  const user = await getAuthUser();
  if (!user) return { ok: false, error: 'Not signed in' };
  if (!canManagePayroll(role)) {
    return { ok: false, error: 'Only owners and managers can mark payouts' };
  }

  const supabase = createAdminClient();
  const { employeeId, periodStart, periodEnd, method, amountPaid, coversDays, idempotencyKey }
    = parsed.data;

  if (!(await assertEmployeeInOrg(supabase, org.id, employeeId))) {
    return { ok: false, error: 'Employee not found' };
  }

  /*
    The cap. Total paid may never exceed total earned so far, because the app
    has no way to claw money back and a negative payday is not a state anybody
    can fix from this screen.

    Deliberately measured against the PERIOD, not the ticked days. Days propose
    the amount; the pot decides whether there is room. Capping against the
    ticked days would refuse $300 of genuinely-earned Thursday work because an
    earlier advance had notionally "used up" days the person had not worked yet.
  */
  const entries = await computePayroll(periodStart, periodEnd);
  const earnedSoFar = entries.find((e) => e.employeeId === employeeId)?.totalCompensation ?? 0;

  const existing = await loadPayouts(periodStart, periodEnd);
  const alreadyPaid = totalPaidTo(existing.filter((p) => p.employeeId === employeeId));

  const capacity = remainingAdvanceCapacity(earnedSoFar, alreadyPaid);
  if (amountPaid > capacity + 0.005) {
    // Both figures named, so the owner can act rather than guess at the rule.
    return {
      ok: false,
      error:
        `That is more than has been earned. ${money(earnedSoFar)} earned so far, ` +
        `${money(alreadyPaid)} already paid — ${money(capacity)} available.`,
    };
  }

  // Insert, not upsert: a period holds many payments now, so there is no
  // natural row to overwrite. Idempotency comes from the unique index on
  // (organization_id, idempotency_key) — a double-tap carries the same key and
  // the second insert conflicts rather than paying twice.
  const { error } = await supabase
    .from('payroll_payouts')
    .upsert(
      {
        organization_id: org.id,
        employee_id:     employeeId,
        period_start:    periodStart,
        period_end:      periodEnd,
        method,
        amount_paid:     amountPaid,
        covers_days:     coversDays ?? null,
        idempotency_key: idempotencyKey,
        paid_at:         new Date().toISOString(),
        marked_by:       user.id,
      },
      { onConflict: 'organization_id,idempotency_key', ignoreDuplicates: true },
    );

  if (error) return { ok: false, error: error.message };

  revalidatePath('/app/payroll');
  return { ok: true };
}

/**
 * Undo one payment.
 *
 * Targets a row rather than a period: a period can hold several payments now,
 * and deleting by (employee, period) would wipe an advance somebody took last
 * week along with today's mistake.
 */
export async function deletePayout(input: { payoutId: string }): Promise<PayoutResult> {
  const parsed = deleteSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'Invalid payout' };
  }

  const { org, role } = await getCurrentOrg();
  const user = await getAuthUser();
  if (!user) return { ok: false, error: 'Not signed in' };
  if (!canManagePayroll(role)) {
    return { ok: false, error: 'Only owners and managers can mark payouts' };
  }

  const supabase = createAdminClient();

  const { error } = await supabase
    .from('payroll_payouts')
    .delete()
    .eq('organization_id', org.id)
    .eq('id', parsed.data.payoutId);

  if (error) return { ok: false, error: error.message };

  revalidatePath('/app/payroll');
  return { ok: true };
}
