'use server';

import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import { createAdminClient } from '@/lib/supabase/admin';
import { getAuthUser, getCurrentOrg } from '@/lib/org';
import { canManagePayroll } from '@/lib/permissions';
import {
  PAYOUT_METHODS, planBulkPayout, remainingAdvanceCapacity, totalPaidTo,
  type BulkPayableEntry, type BulkPayoutSkip, type Payout, type PayoutMethod,
} from '@/lib/payroll/payouts';
import { computePayroll } from './actions';

/**
 * Marking who has actually been paid for a period.
 *
 * Unpaid is the absence of a row, so there are only two writes: insert one, or
 * delete it. See the migration for why there is no status column.
 *
 * Both writes check the caller may manage payroll and that the employee belongs
 * to the caller's bar — `employee_id` arrives from the client, and without that
 * check a crafted id would attach a payout to another bar's staff.
 */

const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Expected YYYY-MM-DD');

/** Whole dollars and cents, for an error message a person has to act on. */
const money = (n: number) =>
  n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });

const markSchema = z.object({
  employeeId:  z.string().uuid(),
  periodStart: isoDate,
  periodEnd:   isoDate,
  method:      z.enum(PAYOUT_METHODS as unknown as [PayoutMethod, ...PayoutMethod[]]),
  // What the run said this person was owed at the moment of marking. Negative
  // is impossible; the ceiling is a typo guard, not a policy.
  amountPaid:  z.number().min(0).max(1_000_000),
  // The nights the amount was worked out from. Null for a whole-period payout,
  // which is what "Mark paid" still does.
  coversDays:  z.array(isoDate).nullable().optional(),
  // Generated by the client when the dialog opens, so the same tap twice
  // collides on the unique index instead of paying somebody a second time.
  idempotencyKey: z.string().uuid(),
});

const deleteSchema = z.object({ payoutId: z.string().uuid() });

export type PayoutResult = { ok: boolean; error?: string };

/** Every payout recorded for the period on screen, keyed by employee. */
export async function loadPayouts(
  periodStart: string,
  periodEnd: string,
): Promise<Payout[]> {
  const { org } = await getCurrentOrg();
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from('payroll_payouts')
    .select('id, employee_id, method, amount_paid, paid_at, covers_days')
    .eq('organization_id', org.id)
    .eq('period_start', periodStart)
    .eq('period_end', periodEnd)
    // Oldest first: the payments list reads as a history, and an advance
    // precedes the settlement it was taken against.
    .order('paid_at', { ascending: true });

  // Throw rather than fall back to `[]`. As of this branch the migration
  // adding `covers_days`/`idempotency_key`
  // (supabase/migrations/20260909000000_payouts_ledger.sql) has not been run
  // anywhere, and this SELECT now names `covers_days` — if it deploys ahead of
  // the migration, PostgREST rejects the query and every caller of this
  // function (the payroll page, markPaid's cap, the NACHA export) would
  // silently read every employee as unpaid. That is worse than a page error:
  // it zeroes `alreadyPaid` in the advance cap and the ACH net-of-advances
  // arithmetic, which is exactly the double-payment C1/I4 exist to prevent.
  // Callers here are server actions and a server page, so throwing surfaces a
  // real error screen instead of rendering a lie.
  if (error) throw new Error(`Failed to load payouts: ${error.message}`);

  return (data ?? []).map((row) => ({
    id:         row.id as string,
    employeeId: row.employee_id as string,
    method:     row.method as PayoutMethod,
    // NUMERIC comes back as a string on some driver versions; the UI formats it.
    amountPaid: Number(row.amount_paid ?? 0),
    paidAt:     row.paid_at as string,
    coversDays: (row.covers_days as string[] | null) ?? null,
  }));
}

/**
 * Every payout whose stored period OVERLAPS [periodStart, periodEnd], across
 * every employee — not the exact match `loadPayouts` (display) uses.
 *
 * The payroll screen offers week and month views over the same days, and an
 * advance is stored under whichever period box was on screen when it was
 * recorded. An exact match would make a week-recorded advance invisible from
 * the month view and let it be paid again on top. Reading wider closes that
 * hole for both places that decide whether money should move: the advance
 * cap in `markPaid`, and the ACH route's net-of-advances arithmetic. Both
 * MUST read through this one function — two separately-written overlap
 * queries drifting apart is exactly how this hole reopened once already
 * (the cap moved to overlap in an earlier pass; the ACH route did not).
 *
 * Direction is deliberate, not incidental: over-deducting (counting a
 * payout that turns out to belong to a different window) UNDERPAYS, which
 * is visible on the pay stub and can be topped up by hand. Under-deducting
 * OVERPAYS via ACH, which is neither visible nor recoverable. This codebase
 * always prefers the safe failure, so both callers read wider rather than
 * narrower.
 *
 * Throws rather than returning `[]` on error, for the same reason as
 * `loadPayouts`: a swallowed error here would zero `alreadyPaid` in both the
 * cap and the ACH arithmetic and silently permit the double payment this
 * function exists to prevent.
 */
export async function loadPayoutsOverlapping(
  periodStart: string,
  periodEnd: string,
): Promise<Payout[]> {
  const { org } = await getCurrentOrg();
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from('payroll_payouts')
    .select('id, employee_id, method, amount_paid, paid_at, covers_days')
    .eq('organization_id', org.id)
    .lte('period_start', periodEnd)
    .gte('period_end', periodStart)
    .order('paid_at', { ascending: true });

  if (error) throw new Error(`Failed to load overlapping payouts: ${error.message}`);

  return (data ?? []).map((row) => ({
    id:         row.id as string,
    employeeId: row.employee_id as string,
    method:     row.method as PayoutMethod,
    amountPaid: Number(row.amount_paid ?? 0),
    paidAt:     row.paid_at as string,
    coversDays: (row.covers_days as string[] | null) ?? null,
  }));
}

/** Confirms the employee is at the caller's bar before anything is written. */
async function assertEmployeeInOrg(
  supabase: ReturnType<typeof createAdminClient>,
  orgId: string,
  employeeId: string,
): Promise<boolean> {
  const { data } = await supabase
    .from('employees')
    .select('id')
    .eq('id', employeeId)
    .eq('organization_id', orgId)
    .maybeSingle();
  return Boolean(data);
}

export async function markPaid(input: {
  employeeId: string;
  periodStart: string;
  periodEnd: string;
  method: PayoutMethod;
  amountPaid: number;
  coversDays?: string[] | null;
  idempotencyKey: string;
}): Promise<PayoutResult> {
  const parsed = markSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'Invalid payout' };
  }

  const { org, role } = await getCurrentOrg();
  const user = await getAuthUser();
  if (!user) return { ok: false, error: 'Not signed in' };
  if (!canManagePayroll(role)) {
    return { ok: false, error: 'Only owners and managers can mark payouts' };
  }

  const supabase = createAdminClient();
  const { employeeId, periodStart, periodEnd, method, amountPaid, coversDays, idempotencyKey }
    = parsed.data;

  if (!(await assertEmployeeInOrg(supabase, org.id, employeeId))) {
    return { ok: false, error: 'Employee not found' };
  }

  /*
    The cap. Total paid may never exceed total earned so far, because the app
    has no way to claw money back and a negative payday is not a state anybody
    can fix from this screen.

    Deliberately measured against the PERIOD, not the ticked days. Days propose
    the amount; the pot decides whether there is room. Capping against the
    ticked days would refuse $300 of genuinely-earned Thursday work because an
    earlier advance had notionally "used up" days the person had not worked yet.

    The cap reads payouts through `loadPayoutsOverlapping`, not the exact
    period match `loadPayouts` (the display) uses — see that function's doc
    comment for why, and why the ACH export's net-of-advances arithmetic reads
    through the SAME function rather than its own query. The consequence is
    the cap can refuse here while the screen shows nothing paid for this exact
    period — which is why the refusal message names both figures rather than
    just the amount.
  */
  const entries = await computePayroll(periodStart, periodEnd);
  const earnedSoFar = entries.find((e) => e.employeeId === employeeId)?.totalCompensation ?? 0;

  const overlapping = await loadPayoutsOverlapping(periodStart, periodEnd);
  const alreadyPaid = totalPaidTo(overlapping.filter((p) => p.employeeId === employeeId));

  const capacity = remainingAdvanceCapacity(earnedSoFar, alreadyPaid);
  if (amountPaid > capacity + 0.005) {
    // Both figures named, so the owner can act rather than guess at the rule.
    // "Already paid" here may exceed what the screen shows for this exact
    // period — it counts every overlapping period view, which is the point.
    return {
      ok: false,
      error:
        `That is more than has been earned. ${money(earnedSoFar)} earned so far, ` +
        `${money(alreadyPaid)} already paid — ${money(capacity)} available.`,
    };
  }

  // Insert, not upsert: a period holds many payments now, so there is no
  // natural row to overwrite. Idempotency comes from the unique index on
  // (organization_id, idempotency_key) plus `ignoreDuplicates: true` below —
  // ON CONFLICT DO NOTHING — so a double-tap carrying the same key does not
  // error and does not insert a second row; it silently does nothing and this
  // call still reports success, rather than paying twice.
  const { error } = await supabase
    .from('payroll_payouts')
    .upsert(
      {
        organization_id: org.id,
        employee_id:     employeeId,
        period_start:    periodStart,
        period_end:      periodEnd,
        method,
        amount_paid:     amountPaid,
        covers_days:     coversDays ?? null,
        idempotency_key: idempotencyKey,
        paid_at:         new Date().toISOString(),
        marked_by:       user.id,
      },
      { onConflict: 'organization_id,idempotency_key', ignoreDuplicates: true },
    );

  if (error) return { ok: false, error: error.message };

  revalidatePath('/app/payroll');
  return { ok: true };
}

const markManySchema = z.object({
  periodStart: isoDate,
  periodEnd:   isoDate,
  method:      z.enum(PAYOUT_METHODS as unknown as [PayoutMethod, ...PayoutMethod[]]),
  // One key PER EMPLOYEE, generated when the dialog opened. Confirming twice
  // therefore replays the same keys and collides on the unique index rather
  // than paying the whole room a second time.
  keys:        z.record(z.string().uuid(), z.string().uuid()),
});

export type BulkPayoutResult = {
  ok:      boolean;
  error?:  string;
  /** How many ledger rows the write actually created. */
  paid:    number;
  total:   number;
  skipped: BulkPayoutSkip[];
};

/**
 * Settle everyone who still has a balance for a period, in one action.
 *
 * DELIBERATELY NOT A CLIENT LOOP OVER markPaid. That would be one round trip
 * and one full computePayroll per employee — a dozen recomputes of the same
 * period to answer the same question — and a failure halfway would leave the
 * browser holding a half-finished payroll with no way to describe it. Here the
 * run is computed once, the overlapping payouts are read once, and the whole
 * set either passes the cap or is named in `skipped`.
 *
 * Every rule the single path enforces is enforced here, through the same
 * functions rather than a second copy: the caller may manage payroll, every
 * employee belongs to this bar, the amount is a BALANCE, and no payment may
 * exceed remainingAdvanceCapacity. A bulk route with a looser rule would be a
 * way around a cap that exists because this app cannot claw money back.
 */
export async function markManyPaid(input: {
  periodStart: string;
  periodEnd: string;
  method: PayoutMethod;
  keys: Record<string, string>;
}): Promise<BulkPayoutResult> {
  const empty = { paid: 0, total: 0, skipped: [] as BulkPayoutSkip[] };

  const parsed = markManySchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'Invalid payout', ...empty };
  }

  const { org, role } = await getCurrentOrg();
  const user = await getAuthUser();
  if (!user) return { ok: false, error: 'Not signed in', ...empty };
  if (!canManagePayroll(role)) {
    return { ok: false, error: 'Only owners and managers can mark payouts', ...empty };
  }

  const { periodStart, periodEnd, method, keys } = parsed.data;
  const supabase = createAdminClient();

  const entries = await computePayroll(periodStart, periodEnd);
  if (entries.length === 0) {
    return { ok: false, error: 'This period has no payroll entries', ...empty };
  }

  // Overlapping, not exact — see loadPayoutsOverlapping. An advance recorded
  // from the week view is invisible to a month-view exact match, and "the
  // balance" computed without it pays that advance again.
  const overlapping = await loadPayoutsOverlapping(periodStart, periodEnd);
  const alreadyPaid = new Map<string, number>();
  for (const entry of entries) {
    alreadyPaid.set(
      entry.employeeId,
      totalPaidTo(overlapping.filter((p) => p.employeeId === entry.employeeId)),
    );
  }

  const payable: BulkPayableEntry[] = entries.map((e) => ({
    employeeId:        e.employeeId,
    employeeName:      e.employeeName,
    totalCompensation: e.totalCompensation,
  }));

  const plan = planBulkPayout(payable, alreadyPaid);
  if (plan.lines.length === 0) {
    return { ok: true, paid: 0, total: 0, skipped: plan.skipped };
  }

  /*
    Org membership for the whole set in ONE query rather than per employee.

    These ids come from computePayroll, which is already scoped to this org, so
    this is belt and braces rather than the primary defence — but the single
    path checks and a bulk path that did not would be the weaker of the two
    doors into the same table. Anyone missing is dropped rather than failing
    the batch: one stale roster row must not stop a bar paying everybody else.
  */
  const { data: inOrg } = await supabase
    .from('employees')
    .select('id')
    .eq('organization_id', org.id)
    .in('id', plan.lines.map((l) => l.employeeId));

  const allowed = new Set((inOrg ?? []).map((e) => e.id as string));
  const lines = plan.lines.filter((l) => allowed.has(l.employeeId));

  // A key per employee is required. Writing without one would hit the NOT NULL
  // on idempotency_key, but failing here names the bug instead of surfacing a
  // constraint violation to somebody paying their staff.
  const missingKey = lines.find((l) => !keys[l.employeeId]);
  if (missingKey) {
    return {
      ok: false,
      error: `No idempotency key for ${missingKey.employeeName} — reopen the dialog and try again.`,
      ...empty,
    };
  }

  const paidAt = new Date().toISOString();

  // One upsert, ON CONFLICT DO NOTHING on (organization_id, idempotency_key).
  // A replayed confirmation inserts nothing and reports what it actually wrote,
  // which is zero — not a second payday.
  //
  // admin-scope-ok: every row sets organization_id to the resolved org, and
  // each employee_id was just confirmed to belong to it by the query above.
  const { data: inserted, error } = await supabase
    .from('payroll_payouts')
    .upsert(
      lines.map((l) => ({
        organization_id: org.id,
        employee_id:     l.employeeId,
        period_start:    periodStart,
        period_end:      periodEnd,
        method,
        amount_paid:     l.amount,
        // Null, exactly as a single "Mark paid" does: this settles the period,
        // not a chosen set of nights.
        covers_days:     null,
        idempotency_key: keys[l.employeeId],
        paid_at:         paidAt,
        marked_by:       user.id,
      })),
      { onConflict: 'organization_id,idempotency_key', ignoreDuplicates: true },
    )
    .select('amount_paid');

  if (error) return { ok: false, error: error.message, ...empty };

  const written = inserted ?? [];

  revalidatePath('/app/payroll');
  return {
    ok:      true,
    // What was WRITTEN, not what was planned. On a replay these are zero, and
    // reporting the plan would tell an owner they had just paid everyone twice.
    paid:    written.length,
    total:   Math.round(written.reduce((s, r) => s + (Number(r.amount_paid) || 0), 0) * 100) / 100,
    skipped: plan.skipped,
  };
}

/**
 * Undo one payment.
 *
 * Targets a row rather than a period: a period can hold several payments now,
 * and deleting by (employee, period) would wipe an advance somebody took last
 * week along with today's mistake.
 */
export async function deletePayout(input: { payoutId: string }): Promise<PayoutResult> {
  const parsed = deleteSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'Invalid payout' };
  }

  const { org, role } = await getCurrentOrg();
  const user = await getAuthUser();
  if (!user) return { ok: false, error: 'Not signed in' };
  if (!canManagePayroll(role)) {
    return { ok: false, error: 'Only owners and managers can mark payouts' };
  }

  const supabase = createAdminClient();

  const { error } = await supabase
    .from('payroll_payouts')
    .delete()
    .eq('organization_id', org.id)
    .eq('id', parsed.data.payoutId);

  if (error) return { ok: false, error: error.message };

  revalidatePath('/app/payroll');
  return { ok: true };
}
