'use server';

import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import { createAdminClient } from '@/lib/supabase/admin';
import { getAuthUser, getCurrentOrg } from '@/lib/org';
import { canManagePayroll } from '@/lib/permissions';
import {
  PAYOUT_METHODS, remainingAdvanceCapacity,
  type Payout, type PayoutMethod,
} from '@/lib/payroll/payouts';
import { computePayroll } from './actions';

/**
 * Marking who has actually been paid for a period.
 *
 * Unpaid is the absence of a row, so there are only two writes: insert one, or
 * delete it. See the migration for why there is no status column.
 *
 * Both writes check the caller may manage payroll and that the employee belongs
 * to the caller's bar — `employee_id` arrives from the client, and without that
 * check a crafted id would attach a payout to another bar's staff.
 */

const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Expected YYYY-MM-DD');

/** Whole dollars and cents, for an error message a person has to act on. */
const money = (n: number) =>
  n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });

const markSchema = z.object({
  employeeId:  z.string().uuid(),
  periodStart: isoDate,
  periodEnd:   isoDate,
  method:      z.enum(PAYOUT_METHODS as unknown as [PayoutMethod, ...PayoutMethod[]]),
  // What the run said this person was owed at the moment of marking. Negative
  // is impossible; the ceiling is a typo guard, not a policy.
  amountPaid:  z.number().min(0).max(1_000_000),
  // The nights the amount was worked out from. Null for a whole-period payout,
  // which is what "Mark paid" still does.
  coversDays:  z.array(isoDate).nullable().optional(),
  // Generated by the client when the dialog opens, so the same tap twice
  // collides on the unique index instead of paying somebody a second time.
  idempotencyKey: z.string().uuid(),
});

const deleteSchema = z.object({ payoutId: z.string().uuid() });

export type PayoutResult = { ok: boolean; error?: string };

/** Every payout recorded for the period on screen, keyed by employee. */
export async function loadPayouts(
  periodStart: string,
  periodEnd: string,
): Promise<Payout[]> {
  const { org } = await getCurrentOrg();
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from('payroll_payouts')
    .select('id, employee_id, method, amount_paid, paid_at, covers_days')
    .eq('organization_id', org.id)
    .eq('period_start', periodStart)
    .eq('period_end', periodEnd)
    // Oldest first: the payments list reads as a history, and an advance
    // precedes the settlement it was taken against.
    .order('paid_at', { ascending: true });

  // Throw rather than fall back to `[]`. As of this branch the migration
  // adding `covers_days`/`idempotency_key`
  // (supabase/migrations/20260909000000_payouts_ledger.sql) has not been run
  // anywhere, and this SELECT now names `covers_days` — if it deploys ahead of
  // the migration, PostgREST rejects the query and every caller of this
  // function (the payroll page, markPaid's cap, the NACHA export) would
  // silently read every employee as unpaid. That is worse than a page error:
  // it zeroes `alreadyPaid` in the advance cap and the ACH net-of-advances
  // arithmetic, which is exactly the double-payment C1/I4 exist to prevent.
  // Callers here are server actions and a server page, so throwing surfaces a
  // real error screen instead of rendering a lie.
  if (error) throw new Error(`Failed to load payouts: ${error.message}`);

  return (data ?? []).map((row) => ({
    id:         row.id as string,
    employeeId: row.employee_id as string,
    method:     row.method as PayoutMethod,
    // NUMERIC comes back as a string on some driver versions; the UI formats it.
    amountPaid: Number(row.amount_paid ?? 0),
    paidAt:     row.paid_at as string,
    coversDays: (row.covers_days as string[] | null) ?? null,
  }));
}

/** Confirms the employee is at the caller's bar before anything is written. */
async function assertEmployeeInOrg(
  supabase: ReturnType<typeof createAdminClient>,
  orgId: string,
  employeeId: string,
): Promise<boolean> {
  const { data } = await supabase
    .from('employees')
    .select('id')
    .eq('id', employeeId)
    .eq('organization_id', orgId)
    .maybeSingle();
  return Boolean(data);
}

export async function markPaid(input: {
  employeeId: string;
  periodStart: string;
  periodEnd: string;
  method: PayoutMethod;
  amountPaid: number;
  coversDays?: string[] | null;
  idempotencyKey: string;
}): Promise<PayoutResult> {
  const parsed = markSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'Invalid payout' };
  }

  const { org, role } = await getCurrentOrg();
  const user = await getAuthUser();
  if (!user) return { ok: false, error: 'Not signed in' };
  if (!canManagePayroll(role)) {
    return { ok: false, error: 'Only owners and managers can mark payouts' };
  }

  const supabase = createAdminClient();
  const { employeeId, periodStart, periodEnd, method, amountPaid, coversDays, idempotencyKey }
    = parsed.data;

  if (!(await assertEmployeeInOrg(supabase, org.id, employeeId))) {
    return { ok: false, error: 'Employee not found' };
  }

  /*
    The cap. Total paid may never exceed total earned so far, because the app
    has no way to claw money back and a negative payday is not a state anybody
    can fix from this screen.

    Deliberately measured against the PERIOD, not the ticked days. Days propose
    the amount; the pot decides whether there is room. Capping against the
    ticked days would refuse $300 of genuinely-earned Thursday work because an
    earlier advance had notionally "used up" days the person had not worked yet.

    The cap reads payouts by INTERVAL OVERLAP, not the exact period match
    `loadPayouts` (the display) uses. The payroll screen offers week and month
    views over the same days, and an advance recorded on the week view is a
    different `period_start`/`period_end` than the month view — an exact match
    would make that advance invisible from the month view and let the whole
    month be paid on top of it. Switching the DISPLAY to overlap instead would
    have the opposite problem: a month-sized payout would count against a week
    view and make a week that was never paid look overpaid — trading one wrong
    figure for another. The cap must never permit an overpayment, so it reads
    wider; the display must not invent payments against a period they were not
    made for, so it stays exact. The consequence is the cap can refuse here
    while the screen shows nothing paid for this exact period — which is why
    the refusal message names both figures rather than just the amount.
  */
  const entries = await computePayroll(periodStart, periodEnd);
  const earnedSoFar = entries.find((e) => e.employeeId === employeeId)?.totalCompensation ?? 0;

  const { data: overlapping, error: overlapError } = await supabase
    .from('payroll_payouts')
    .select('amount_paid')
    .eq('organization_id', org.id)
    .eq('employee_id', employeeId)
    .lte('period_start', periodEnd)
    .gte('period_end', periodStart);

  // Same reasoning as loadPayouts: a swallowed error here would zero
  // `alreadyPaid` and let the cap wave through an amount that has, in truth,
  // already been paid via a different period view.
  if (overlapError) throw new Error(`Failed to check existing payouts: ${overlapError.message}`);

  const alreadyPaid = (overlapping ?? [])
    .reduce((sum, p) => sum + (Number(p.amount_paid) || 0), 0);

  const capacity = remainingAdvanceCapacity(earnedSoFar, alreadyPaid);
  if (amountPaid > capacity + 0.005) {
    // Both figures named, so the owner can act rather than guess at the rule.
    // "Already paid" here may exceed what the screen shows for this exact
    // period — it counts every overlapping period view, which is the point.
    return {
      ok: false,
      error:
        `That is more than has been earned. ${money(earnedSoFar)} earned so far, ` +
        `${money(alreadyPaid)} already paid — ${money(capacity)} available.`,
    };
  }

  // Insert, not upsert: a period holds many payments now, so there is no
  // natural row to overwrite. Idempotency comes from the unique index on
  // (organization_id, idempotency_key) plus `ignoreDuplicates: true` below —
  // ON CONFLICT DO NOTHING — so a double-tap carrying the same key does not
  // error and does not insert a second row; it silently does nothing and this
  // call still reports success, rather than paying twice.
  const { error } = await supabase
    .from('payroll_payouts')
    .upsert(
      {
        organization_id: org.id,
        employee_id:     employeeId,
        period_start:    periodStart,
        period_end:      periodEnd,
        method,
        amount_paid:     amountPaid,
        covers_days:     coversDays ?? null,
        idempotency_key: idempotencyKey,
        paid_at:         new Date().toISOString(),
        marked_by:       user.id,
      },
      { onConflict: 'organization_id,idempotency_key', ignoreDuplicates: true },
    );

  if (error) return { ok: false, error: error.message };

  revalidatePath('/app/payroll');
  return { ok: true };
}

/**
 * Undo one payment.
 *
 * Targets a row rather than a period: a period can hold several payments now,
 * and deleting by (employee, period) would wipe an advance somebody took last
 * week along with today's mistake.
 */
export async function deletePayout(input: { payoutId: string }): Promise<PayoutResult> {
  const parsed = deleteSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'Invalid payout' };
  }

  const { org, role } = await getCurrentOrg();
  const user = await getAuthUser();
  if (!user) return { ok: false, error: 'Not signed in' };
  if (!canManagePayroll(role)) {
    return { ok: false, error: 'Only owners and managers can mark payouts' };
  }

  const supabase = createAdminClient();

  const { error } = await supabase
    .from('payroll_payouts')
    .delete()
    .eq('organization_id', org.id)
    .eq('id', parsed.data.payoutId);

  if (error) return { ok: false, error: error.message };

  revalidatePath('/app/payroll');
  return { ok: true };
}
