using RailAgent.Config;

namespace RailAgent.Setup;

/// <summary>
/// Brings a config written by an older setup up to what this build expects.
///
/// WHY THIS EXISTS
///
/// rail-update.exe replaces the binary. It cannot touch the schema mapping,
/// because for a 2Touch install the ENTIRE derived table lives in
/// appsettings.local.json — the SELECT, the UNIONs, the column aliases. A box
/// upgraded to 1.1.0 therefore keeps running its old four-column Z query and
/// reports no cash/card split, forever, until a human walks over to that POS
/// and re-runs setup.
///
/// That is a bad trade for a feature whose whole point is unattended upgrades,
/// so the new binary recognises the old query and substitutes the current one.
///
/// WHY IT MATCHES THE WHOLE TEXT
///
/// Only a config whose Z source is EXACTLY a known profile version is upgraded
/// (whitespace and line endings aside — the wizard writes JSON, and JSON
/// escaping round-trips newlines differently on different machines).
///
/// A looser check — "does it mention tblSalesHistPmnts" — would also match a
/// profile someone has since hand-edited, and silently throw their edit away.
/// The README explicitly invites hand-editing Tables.* , so that is a real
/// person's real work, not a hypothetical. Exact match means the only thing
/// this can ever replace is text the wizard itself generated.
///
/// IN MEMORY ONLY
///
/// The file on disk is left alone. It holds this bar's agent token and SQL
/// credentials, and rewriting it from a background service to gain a column
/// mapping is not worth the chance of mangling them. The migration is cheap
/// and deterministic, so re-deriving it at every start costs nothing.
/// </summary>
public static class ProfileMigration
{
    /// <summary>
    /// The Z source generated by setup up to and including 1.0.0: four columns,
    /// no tender split. Kept verbatim because it is a fingerprint — if it drifts
    /// from what those installs actually have, the migration simply stops
    /// matching, and the bar is no worse off than before this existed.
    /// </summary>
    public const string ZReportV1 = """
        (
            SELECT h.dtmTicketDate          AS BusinessDate,
                   h.fNetAmt                AS NetSales,
                   CAST(0 AS FLOAT)         AS CcTips,
                   CAST(0 AS FLOAT)         AS CashTips
            FROM dbo.tblSalesHdrHist h
            WHERE h.dtmTicketDate >= '{cutoff}'
            UNION ALL
            SELECT h.dtmTicketDate, h.fNetAmt, 0, 0
            FROM dbo.tblSalesDailyHdr h
            WHERE h.dtmTicketDate >= '{cutoff}'
            UNION ALL
            SELECT p.dtmPmntDate, 0,
                   CASE WHEN p.lPaymentType IN (2, 7) THEN ISNULL(p.fTipAmt, 0) ELSE 0 END,
                   CASE WHEN p.lPaymentType = 0                               THEN ISNULL(p.fTipAmt, 0) ELSE 0 END
            FROM dbo.tblSalesHistPmnts p
            WHERE p.dtmPmntDate >= '{cutoff}'
            UNION ALL
            SELECT p.dtmPmntDate, 0,
                   CASE WHEN p.lPaymentType IN (2, 7) THEN ISNULL(p.fTipAmt, 0) ELSE 0 END,
                   CASE WHEN p.lPaymentType = 0                               THEN ISNULL(p.fTipAmt, 0) ELSE 0 END
            FROM dbo.tblSalesDailyPmnts p
            WHERE p.dtmPmntDate >= '{cutoff}'
        ) AS rail_z
        """;

    /// <summary>
    /// Upgrades <paramref name="cfg"/> in place. Safe to call repeatedly; a
    /// config that is already current, hand-mapped, or hand-edited is untouched.
    ///
    /// TWO ERAS ARE RECOGNISED, because there are two of them in the field:
    ///
    ///   • Up to 1.0.0 — the four-column Z source, no tender split. Its whole
    ///     Z mapping is replaced.
    ///   • 1.0.2 to 1.2.x — the CURRENT six-column Z source, but written before
    ///     HourlySales and ServerSales existed. Nothing about its Z feed is
    ///     wrong, so only the missing feeds are filled in.
    ///
    /// The second era was invisible for a release. The Z source has been
    /// byte-identical since 1.0.2, so those boxes never match the V1
    /// fingerprint and fell through Apply untouched — reporting no hourly or
    /// per-server trade forever, through any number of rail-update.exe runs,
    /// because the binary is the only thing an update replaces.
    /// </summary>
    public static void Apply(AgentConfig cfg)
    {
        if (IsSameSql(cfg.Tables.ZReport, ZReportV1))
        {
            // Replaced wholesale rather than patched: the aliases the column map
            // points at only exist because this exact text puts them there, so the
            // two have to move together.
            cfg.Tables.ZReport = TwoTouchProfile.ZReport.Source;
            cfg.Columns.ZReport.CashSales = "[CashSales]";
            cfg.Columns.ZReport.CardSales = "[CardSales]";

            // 2Touch's ticket dates carry the time, which is what makes the
            // business-day cutoff meaningful. Older configs never wrote the flag at
            // all (see LocalConfigWriter), so it is restated here alongside the
            // source that guarantees it.
            cfg.Columns.ZReport.DateHasTime = true;

            AddFeedsThatDidNotExistYet(cfg);
            cfg.ProfileUpgraded = true;
            return;
        }

        // Already on the current Z source. That text is only ever produced by
        // TwoTouchProfile itself, so matching it is the same proof of "this is
        // a wizard-written 2Touch config" that the V1 fingerprint gives — and
        // the same reason it is safe to hand this box queries against
        // tblSalesHdrHist, which its Z and EW feeds already read every cycle.
        if (IsSameSql(cfg.Tables.ZReport, TwoTouchProfile.ZReport.Source))
        {
            if (AddFeedsThatDidNotExistYet(cfg)) cfg.ProfileUpgraded = true;
        }
    }

    /// <summary>
    /// Fills in HourlySales and ServerSales when this config has never heard of
    /// them, and reports whether anything was actually written.
    ///
    /// ONLY A BLANK IS FILLED. An empty Tables entry is how the whole agent
    /// spells "this bar has no such feed" (SyncService.Enabled), and it is also
    /// what a config predating the feed binds to — the two are genuinely
    /// indistinguishable here, and filling it is the reading that matches what
    /// Apply already did for every V1 config. A NON-empty value is somebody's
    /// answer, hand-written or wizard-chosen, and is never replaced.
    ///
    /// Routed through TwoTouchProfile.Apply rather than assigning the columns
    /// here, so the mapping has exactly one definition. That also carries
    /// DateHasTime, which Hourly is gated on in addition to Enabled() — wiring
    /// the table without it produces a feed skipped on every cycle, which is a
    /// silent no-op wearing the shape of a fix.
    /// </summary>
    private static bool AddFeedsThatDidNotExistYet(AgentConfig cfg)
    {
        var wrote = false;

        if (string.IsNullOrWhiteSpace(cfg.Tables.HourlySales))
        {
            TwoTouchProfile.Apply(TwoTouchProfile.HourlySales, cfg);
            cfg.Columns.HourlySales.DateHasTime = true;
            wrote = true;
        }

        if (string.IsNullOrWhiteSpace(cfg.Tables.ServerSales))
        {
            TwoTouchProfile.Apply(TwoTouchProfile.ServerSales, cfg);
            cfg.Columns.ServerSales.DateHasTime = true;
            wrote = true;
        }

        return wrote;
    }

    /// <summary>
    /// Compares two SQL fragments ignoring only what cannot carry meaning:
    /// line endings, and trailing whitespace on a line. Indentation inside a
    /// line is still significant, so this stays a fingerprint match rather than
    /// a fuzzy one.
    /// </summary>
    private static bool IsSameSql(string? a, string? b)
    {
        if (a is null || b is null) return false;

        static string Normalize(string s) => string.Join(
            '\n',
            s.Replace("\r\n", "\n").Replace('\r', '\n')
             .Split('\n')
             .Select(line => line.TrimEnd()))
            .Trim();

        return string.Equals(Normalize(a), Normalize(b), StringComparison.Ordinal);
    }
}
