using RailAgent.Config;

namespace RailAgent.Setup;

/// <summary>
/// Brings a config written by an older setup up to what this build expects.
///
/// WHY THIS EXISTS
///
/// rail-update.exe replaces the binary. It cannot touch the schema mapping,
/// because for a 2Touch install the ENTIRE derived table lives in
/// appsettings.local.json — the SELECT, the UNIONs, the column aliases. A box
/// upgraded to 1.1.0 therefore keeps running its old four-column Z query and
/// reports no cash/card split, forever, until a human walks over to that POS
/// and re-runs setup.
///
/// That is a bad trade for a feature whose whole point is unattended upgrades,
/// so the new binary recognises the old query and substitutes the current one.
///
/// WHY IT MATCHES THE WHOLE TEXT
///
/// Only a config whose Z source is EXACTLY a known profile version is upgraded
/// (whitespace and line endings aside — the wizard writes JSON, and JSON
/// escaping round-trips newlines differently on different machines).
///
/// A looser check — "does it mention tblSalesHistPmnts" — would also match a
/// profile someone has since hand-edited, and silently throw their edit away.
/// The README explicitly invites hand-editing Tables.* , so that is a real
/// person's real work, not a hypothetical. Exact match means the only thing
/// this can ever replace is text the wizard itself generated.
///
/// IN MEMORY ONLY
///
/// The file on disk is left alone. It holds this bar's agent token and SQL
/// credentials, and rewriting it from a background service to gain a column
/// mapping is not worth the chance of mangling them. The migration is cheap
/// and deterministic, so re-deriving it at every start costs nothing.
/// </summary>
public static class ProfileMigration
{
    /// <summary>
    /// The Z source generated by setup up to and including 1.0.0: four columns,
    /// no tender split. Kept verbatim because it is a fingerprint — if it drifts
    /// from what those installs actually have, the migration simply stops
    /// matching, and the bar is no worse off than before this existed.
    /// </summary>
    public const string ZReportV1 = """
        (
            SELECT h.dtmTicketDate          AS BusinessDate,
                   h.fNetAmt                AS NetSales,
                   CAST(0 AS FLOAT)         AS CcTips,
                   CAST(0 AS FLOAT)         AS CashTips
            FROM dbo.tblSalesHdrHist h
            WHERE h.dtmTicketDate >= '{cutoff}'
            UNION ALL
            SELECT h.dtmTicketDate, h.fNetAmt, 0, 0
            FROM dbo.tblSalesDailyHdr h
            WHERE h.dtmTicketDate >= '{cutoff}'
            UNION ALL
            SELECT p.dtmPmntDate, 0,
                   CASE WHEN p.lPaymentType IN (2, 7) THEN ISNULL(p.fTipAmt, 0) ELSE 0 END,
                   CASE WHEN p.lPaymentType = 0                               THEN ISNULL(p.fTipAmt, 0) ELSE 0 END
            FROM dbo.tblSalesHistPmnts p
            WHERE p.dtmPmntDate >= '{cutoff}'
            UNION ALL
            SELECT p.dtmPmntDate, 0,
                   CASE WHEN p.lPaymentType IN (2, 7) THEN ISNULL(p.fTipAmt, 0) ELSE 0 END,
                   CASE WHEN p.lPaymentType = 0                               THEN ISNULL(p.fTipAmt, 0) ELSE 0 END
            FROM dbo.tblSalesDailyPmnts p
            WHERE p.dtmPmntDate >= '{cutoff}'
        ) AS rail_z
        """;

    /// <summary>
    /// Upgrades <paramref name="cfg"/> in place. Safe to call repeatedly; a
    /// config that is already current, hand-mapped, or hand-edited is untouched.
    /// </summary>
    public static void Apply(AgentConfig cfg)
    {
        if (!IsSameSql(cfg.Tables.ZReport, ZReportV1)) return;

        // Replaced wholesale rather than patched: the aliases the column map
        // points at only exist because this exact text puts them there, so the
        // two have to move together.
        cfg.Tables.ZReport = TwoTouchProfile.ZReport.Source;
        cfg.Columns.ZReport.CashSales = "[CashSales]";
        cfg.Columns.ZReport.CardSales = "[CardSales]";

        // 2Touch's ticket dates carry the time, which is what makes the
        // business-day cutoff meaningful. Older configs never wrote the flag at
        // all (see LocalConfigWriter), so it is restated here alongside the
        // source that guarantees it.
        cfg.Columns.ZReport.DateHasTime = true;

        cfg.ProfileUpgraded = true;
    }

    /// <summary>
    /// Compares two SQL fragments ignoring only what cannot carry meaning:
    /// line endings, and trailing whitespace on a line. Indentation inside a
    /// line is still significant, so this stays a fingerprint match rather than
    /// a fuzzy one.
    /// </summary>
    private static bool IsSameSql(string? a, string? b)
    {
        if (a is null || b is null) return false;

        static string Normalize(string s) => string.Join(
            '\n',
            s.Replace("\r\n", "\n").Replace('\r', '\n')
             .Split('\n')
             .Select(line => line.TrimEnd()))
            .Trim();

        return string.Equals(Normalize(a), Normalize(b), StringComparison.Ordinal);
    }
}
